### PR TITLE
Add option to skip push index.yaml

### PR DESCRIPTION
**Pull request by ddzero2c**
As title.
So that I could just upload artifact without publishing to github page.

With this option I could use the other way to publish my charts.

### CODE REVIEW

**Comment by kir4h** [comment]
@ddzero2c any chance of manually adding reviewers? (not sure if allowed by the PR creator, or it is supposed to happen automatically)

**Comment by ddzero2c** [comment]
@kir4h it's not allowed.

**Comment by kir4h** [comment]
@cpanato just curious, how are reviewers assigned? (mentioning you as I've seen you've been involved in other PR reviews)

**Comment by cpanato** [comment]
@kir4h missed this one, will take a look soon

**Comment by kir4h** [comment]
> @kir4h missed this one, will take a look soon

great, thank you!

**Comment by kir4h** [comment]
> @kir4h friendly ping

I´m not a maintainer for this repo, was just trying to get this moved as I think it´s an interesting feature.

@cpanato @davidkarlsen were you able to take a look at this one? Thanks!

**Pull request closed without merging**
