### PR TITLE
Added: --packages-with-index parameter

### PR DESCRIPTION
**Pull request by valeriano-manassero**
Added flag `--package-with-index` implemented in https://github.com/helm/chart-releaser/pull/304.

Implements #147

### CODE REVIEW

**Comment by jasonmoore2k** [comment]
I tested your revision and while the path in the index became relative, the chat file was published in the release rather than in the git repo alongside the index file.

**Comment by immae1** [comment]
Hi @valeriano-manassero Any chance of you resolving the conflicts and completing the PR? Because @jasonmoore2k seems to be right, I've tested the action on my side - but unfortunately the tar file is not stored in my gh-pages branch. I've had a look at your code and in theory its fine, but you've missed two flags (--push and --index-path .) that need to be set regarding the CR binary docs: https://github.com/helm/chart-releaser#usage 

adjustments on my side:
`  if [[ -n "$packages_with_index" ]]; then
        args+=(--packages-with-index --push --skip-existing)`
        
and:
`  if [[ -n "$packages_with_index" ]]; then
        args+=(--packages-with-index --index-path .)
    fi`
    
Best

**Comment by valeriano-manassero** [comment]
Thanks for suggestions; I hope I didn't messed up anything during rebase but it should be good now.

**Comment by jasonmoore2k** [comment]
packages_with_existing needs a default value at top of main()

Also, fails when packaging multiple charts in a single job with a “Updates were rejected because a pushed branch tip is behind its remote counterpart”

**Comment by jasonmoore2k** [comment]
Dug further and the multi-push issue should be fixed by [this PR](https://github.com/helm/chart-releaser/pull/314).

**Comment by valeriano-manassero** [comment]
@cpanato there is anything blocking this one?
Don't want to put any pressure but I guess it useful to have this since chart-releaser is already capable of doing it.
Thanks.

**Comment by nicklausbrown** [comment]
any idea when this will be available once merged? @valeriano-manassero thanks for the contributions and @jasonmoore2k thanks for the reviews!

**Review by cpanato — APPROVED** [review]
lgtm

**Pull request merged**
