### PR TITLE
Skip packaging option - resolves #108

### LINKED ISSUE #108: Add skip-packaging option
after reading through the PRs and issues on this project, it seems there are a number of requests for more custom packaging. These include things like tagging the chart based on git tags or just supporting the option to trigger on tag. I was, too, running into an issue like this. 

my specific issue is that I wanted to be able to tag a commit and have the chart packaged with that tag for the chart version and the app version. 

but... I think that all of these specific packaging options are going to be difficult to maintain over time, so I propose another solution. Add a variable to "skip-packaging". this option would skip the packaging altogether and allow the user to do their own custom packaging in an earlier step. 

I have made the modifications to this project to allow for this and will submit a PR shortly after I get the docs updated.

### PR DESCRIPTION
**Pull request by gmorse81**
This change resolves #108 by adding the option to skip the packaging step altogether.

### CODE REVIEW

**Review by davidkarlsen — APPROVED** [review]
lgtm.
@cpanato - wdyt?

**Review by cpanato — CHANGES_REQUESTED** [review]
looks good to me, but can you add a test that exercise this use case here https://github.com/helm/chart-releaser-action/blob/main/.github/workflows/test-action.yml ?

thanks for this PR

**Comment by davidkarlsen** [comment]
Any update here @gmorse81 ?

**Comment by ivan-penchev** [comment]
Came randomly from a yt recommendation: https://www.youtube.com/watch?v=CML6vfKjQss

**Comment by AbdelrhmanHamouda** [comment]
also came here through a youtube video. @gmorse81, it would be awesome to progress this PR instead if being stuck in a limbo for long. the main repo is progressing and eventually this will be outdated!

**Comment by ben-codner-rs** [comment]
I would also find this useful. We utilize an umbrella setup so I also needed to do my own packaging to make sure I handle subcharts.

**Comment by cpanato** [comment]
> lgtm. @cpanato - wdyt?

lgtm, sorry for the delay

**Comment by Amitk3293** [comment]
Warning: Unexpected input(s) 'skip_packaging', valid inputs are ['version', 'config', 'charts_dir', 'charts_repo_url', 'install_dir', 'install_only']

Still not working I guess, of course I'm using the latest version

**Comment by AbdelrhmanHamouda** [comment]
unless that you are using latest changes, this PR hasn't been included in a release yet

**Comment by davidkarlsen** [comment]
Until we do a release you can use main as the version in order to test it.

**Comment by Amitk3293** [comment]
Oh, haven't noticed that 🥲 .
Thanks guys

**Pull request merged**
