### PR TITLE
Add index_md_path option to copy index.md path based on any file in the repository

### PR DESCRIPTION
**Pull request by vboulineau**
Add option to publish a file (typically `README.md`) to the GH Pages, allowing to easily display a homepage on Helm charts URL.

### CODE REVIEW

**Comment by plumdog** [comment]
I have an interest in this feature, but it looks like it has stalled and now has conflicts.

If this were rebased (which I am willing to try to help with) might this feature get merged?

**Comment by vboulineau** [comment]
Hey @plumdog,

I am also still interested to get this merge, and I can surely rebase it. However we'd some feedbacks from maintainers.

**Comment by cpanato** [comment]
I'm ok with this change, need some rebase and also I would like to see comments from @scottrigby / @davidkarlsen / @unguiculus

**Comment by unguiculus** [comment]
I'll have a look.

**Comment by unguiculus** [comment]
What's the rationale behind this? Why don't you just add an index file once to the gh-pages branch? Why does that have to happen on every release?

**Comment by vboulineau** [comment]
Because file content can change, the idea is to automate the publication. For instance if I want the `README.md` file to be `index.md`, I don't want the developer to have to think about copying the `README.md` to `index.md` in `gh-pages` whenever there is a change to it.

**Comment by davidkarlsen** [comment]
I'm inclined to close this. I think it's an edge-case that's outside of scope for the action. This can be solved with vanilla github-actions configs.

**Pull request closed without merging**
